# SPDX-License-Identifier: Apache-2.0
# XIAO nRF54L15 - Audio recorder to SD card (hardware SPI)

# Console / logging -- PRINTK only
CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=n
CONFIG_RING_BUFFER_LARGE=y

# GPIO (button, LED)
CONFIG_GPIO=y

# Bus / drivers
CONFIG_SPI=y
CONFIG_AUDIO=y
CONFIG_AUDIO_DMIC=y

# SD card
CONFIG_SDHC=y
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_SD_RETRY_COUNT=5
CONFIG_SD_CMD_RETRIES=3
CONFIG_SD_DATA_RETRIES=3
CONFIG_SD_DATA_TIMEOUT=2000
CONFIG_SD_CMD_TIMEOUT=300

# Hardware watchdog
CONFIG_WATCHDOG=y

# System OFF (ultra-low-power sleep)
CONFIG_POWEROFF=y

# FAT filesystem
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_LFN=y
CONFIG_FS_FATFS_LFN_MODE_STACK=y

# Stacks / heap
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_IDLE_STACK_SIZE=2048
