# SPDX-License-Identifier: Apache-2.0
# XIAO nRF54L15 - Audio recorder (BATTERY / PRODUCTION)
# Overlay: west build ... -- -DOVERLAY_CONFIG="prj_battery.conf"
# UART disabled: required for boot from 3.7V LiPo on HW rev v1.0
# Logs via RTT only (J-Link RTT Viewer)

# RTT console (no UART)
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n
CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n
CONFIG_STDOUT_CONSOLE=n
